[client]
showErrorDetails = true

[logger]
level = "debug"

[server]
port = 8501
headless = true
enableXsrfProtection = false
runOnSave = true
maxUploadSize = 200

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
